M48
; DRILL file {KiCad 9.0.6} date 2025-11-25T14:35:32-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-11-25T14:35:32-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.300
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.300
%
G90
G05
T1
X113.0Y-99.0
T2
X100.825Y-103.155
M30
